obstacle_range: 2.5
raytrace_range: 3.0
#robot_radius: 0.165
#footprint: [[0.0,0.19],[-0.20,0.19],[-0.20,-0.19],[0.0,-0.19],[0.17,-0.19],[0.25,0.0],[0.17,0.19]]

#footprint: [[0.0,0.18],[-0.18,0.18],[-0.18,-0.18],[0.0,-0.18],[0.17,-0.18],[0.25,0.0],[0.17,0.18]]

footprint: [[0.0,0.17],[-0.17,0.17],[-0.17,-0.17],[0.0,-0.17],[0.17,-0.17],[0.25,0.0],[0.17,0.17]]

inflation_radius: 0.3
max_obstacle_height: 0.6
min_obstacle_height: 0.0

#observation_sources: scan
#scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
#scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0, #observation_persistence: 0.0}
