global_costmap:
   global_frame: /map
   robot_base_frame: /base_footprint
   update_frequency: 3.0
   publish_frequency: 3.0
   static_map: true
   rolling_window: false
   resolution: 0.02
   transform_tolerance: 1.0
   map_type: costmap

   observation_sources: scan
   scan: {data_type: LaserScan, topic: /scan, marking: false, clearing: false, expected_update_rate: 0, observation_persistence: 0.0}
